#apiVersion: v1
#kind: Namespace
#metadata:
#  name: alp
#
#---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alp-admin
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alp-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: alp-admin
  namespace: kube-system